services:
  - type: web
    name: tiktok-country-leaderboard
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18